version: '3.8'
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube/config:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/date
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/temp:/opt/sonarqube/temp
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar
    depends_on:
      - postgresql

  postgresql:
    image: postgres:alpine3.17
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonat