version: '3'

services:

  # MySQL database
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  # PostgreSQL database
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  # Kafka and MirrorMaker
  kafka:
    image: wurstmeister/kafka:2.12-2.8.0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic1:1:1"
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always

  # MirrorMaker
  mirrormaker:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - kafka
      - mysql
      - postgres
    environment:
      # Configure MirrorMaker to replicate from MySQL to PostgreSQL
      MIRRORED_TOPICS: "topic1"
      SOURCE_CLUSTER_BOOTSTRAP_SERVERS: kafka:9092
      SOURCE_CLUSTER_SECURITY_PROTOCOL: PLAINTEXT
      SOURCE_CLUSTER_SASL_MECHANISM: PLAIN
      SOURCE_CLUSTER_GROUP_ID: mirrormaker
      DESTINATION_CLUSTER_BOOTSTRAP_SERVERS: kafka:9092
      DESTINATION_CLUSTER_SECURITY_PROTOCOL: PLAINTEXT
      DESTINATION_CLUSTER_SASL_MECHANISM: PLAIN
      DESTINATION_CLUSTER_GROUP_ID: mirrormaker
      DESTINATION_CLUSTER_CONFIG_STORAGE_TOPIC: __mirror_maker_config
      DESTINATION_CLUSTER_OFFSET_STORAGE_TOPIC: __mirror_maker_offsets
      DESTINATION_CLUSTER_STATUS_STORAGE_TOPIC: __mirror_maker_status
      DESTINATION_CLUSTER_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      DESTINATION_CLUSTER_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      DESTINATION_CLUSTER_STATUS_STORAGE_REPLICATION_FACTOR: 1
      DESTINATION_CLUSTER_AUTO_OFFSET_RESET: earliest
    command: /bin/bash -c "echo 'bootstrap.servers=kafka:9092' > /tmp/client.properties && /usr/bin/connect-mirror-maker /etc/mirror-maker/mirror-maker.properties"

    volumes:
      - ./mirror-maker.properties:/etc/mirror-maker/mirror-maker.properties
      - ./client.properties:/tmp/client.properties
