version: '3'
services:
    zookeeper_instance_1:
        container_name: zookeeper_instance_1
        image: quay.io/debezium/zookeeper
        ports:
            - 12181:2181
            - 12888:2888
            - 13888:3888
    zookeeper_instance_2:
        container_name: zookeeper_instance_2
        image: quay.io/debezium/zookeeper
        ports:
            - 12182:2181
            - 12889:2888
            - 13889:3888
    kafka_instance_1:
        container_name: kafka_instance_1
        image: quay.io/debezium/kafka
        environment:
            ZOOKEEPER_CONNECT: zookeeper_instance_1:2181,zookeeper_instance_2:2181
            BROKER_ID: 1
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_instance_1:9091,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19091
            KAFKA_LISTENERS: INTERNAL://kafka_instance_1:9091,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19091
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        depends_on:
            - zookeeper_instance_1
            - zookeeper_instance_2
        ports:
            - 9091:9091
    kafka_instance_2:
        container_name: kafka_instance_2
        image: quay.io/debezium/kafka
        environment:
            ZOOKEEPER_CONNECT: zookeeper_instance_1:2181,zookeeper_instance_2:2181
            BROKER_ID: 2
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_instance_2:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092
            KAFKA_LISTENERS: INTERNAL://kafka_instance_2:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        depends_on:
            - zookeeper_instance_1
            - zookeeper_instance_2
        ports:
            - 9092:9092
    kafka_instance_3:
        container_name: kafka_instance_3
        image: quay.io/debezium/kafka
        environment:
            ZOOKEEPER_CONNECT: zookeeper_instance_1:2181,zookeeper_instance_2:2181
            BROKER_ID: 3
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_instance_3:9093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19093
            KAFKA_LISTENERS: INTERNAL://kafka_instance_3:9093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        depends_on:
            - zookeeper_instance_1
            - zookeeper_instance_2
        ports:
            - 9093:9093
    mysql:
        container_name: mysql
        environment:
            MYSQL_PASSWORD: mysqlpw
            MYSQL_ROOT_PASSWORD: debezium
            MYSQL_USER: mysqluser
        image: quay.io/debezium/example-mysql
        ports:
            - 3307:3306
    connect:
        container_name: connect
        environment:
            OFFSET_STORAGE_TOPIC: my_connect_offsets
            STATUS_STORAGE_TOPIC: my_connect_statuses
            CONFIG_STORAGE_TOPIC: my_connect_configs
            GROUP_ID: '1'
            BOOTSTRAP_SERVERS: kafka_instance_1:9091,kafka_instance_2:9092,kafka_instance_3:9093
        image: quay.io/debezium/connect
        depends_on:
            - zookeeper_instance_1
            - zookeeper_instance_2
            - kafka_instance_1
            - kafka_instance_2
            - kafka_instance_3
            - mysql
        ports:
            - 8083:8083
    kafdrop:
        container_name: kafdrop
        environment:
            KAFKA_BROKERCONNECT: kafka_instance_1:9091,kafka_instance_2:9092,kafka_instance_3:9093
        image: obsidiandynamics/kafdrop
        ports:
            - 9000:9000

# http://localhost:9000/topic/dbserver1.inventory.addresses
# http://localhost:8083/connectors

# Postman
# curl --location --request POST 'http://localhost:8083/connectors' \
# --header 'Content-Type: application/json' \
# --data-raw '{
#  "name": "inventory-connector",  
#  "config": {  
#    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
#    "tasks.max": "1",  
#    "database.hostname": "mysql",  
#    "database.port": "3306",
#    "database.user": "debezium",
#    "database.password": "dbz",
#    "database.server.id": "1",  
#    "database.server.name": "dbserver1",  
#    "database.include.list": "inventory",  
#    "database.history.kafka.bootstrap.servers": "kafka_instance_1:9091,kafka_instance_2:9092,kafka_instance_3:9093",  
#    "database.history.kafka.topic": "schema-changes.inventory"  
#  }
# }'